[package]
name = "suo-parser-core"
version = "0.2.0"
edition = "2021"
description = "A timeline parser for FFXIV/ACT plugins"
authors = ["Maiko Tan <maiko.tan.coding@gmail.com>"]
license = "MIT"
repository = "https://github.com/MaikoTan/suo-parser"

[lib]
crate-type = ["rlib", "cdylib"]

[profile.release]
# This makes the compiled code faster and smaller, but it makes compiling slower,
# so it's only enabled in release mode.
lto = true

[dependencies]

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so it's only enabled
# in debug mode.
[target."cfg(debug_assertions)".dependencies]
console_error_panic_hook = "0.1.5"

[dev-dependencies]
insta = { version = "1.43.1", features = ["yaml"] }
